version: '2'
volumes:
  root-cache: {}

services:
  builder:
    image: "${HASKELL_IMAGE}"
    volumes:
      - root-cache:/root/.stack
      - /var/run/docker.sock:/var/run/docker.sock
      - "${DOCKER_EXEC}:/usr/local/bin/docker"
      - ./builder:/opt/builder
      - ./work:/home/build
    command: "/opt/builder/build ${PROJECT_EXEC} ${OUTPUT_CONTAINER}"
