version: '2'
volumes:
  root-cache: {}

services:
  builder:
    build: ./builder
    volumes:
      - root-cache:/root/.stack
      - ./work:/home/build
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
