#!/usr/bin/env bash
set -e

cd /home/build
stack setup --allow-different-user
stack build --allow-different-user
stack_bin="$(stack path --local-install-root --allow-different-user)/bin"

mkdir -p /opt/work/out

cp "$stack_bin/$1" /opt/work/out/exec

cd /opt/work
cp /opt/builder/Dockerfile.scratch Dockerfile
docker build -t "$2" .
